Validate -bootclasspath option explicitly
Summary:
A number of Buck users building Android projects
complain of errors like:

  Fatal Error: Unable to find package java.lang in classpath or bootclasspath

The root cause is Buck passing an Android SDK directory which doesn't
exist to `javac` via the `-bootclasspath` argument.

This adds a validator to ensure that directory exists so we can raise a
more useful error in this case.

Test Plan: Unit tests added. `ant java-test -Dtest.class=JavacStepTest`

Reviewed By: marcinkosiba

fbshipit-source-id: 23a399e