Log stdout and stderr when process finishes with unexpected result
Summary: We are seeing failures such as `Error: [.../clang, --version] exited with unexpected return code 1` without any further information. Instead of swallowing stdout and stderr and fail with no information, we should instead include those in the logs.

Test Plan:
Make a dummy app that returns 1 and prints to stdout and stderr:

    #include <cstdio>
    int main() {
      fprintf(stdout, "out message: line 1\n");
      fprintf(stderr, "error message: line 1\n");
      fprintf(stderr, "error message: line 2\n");
      fprintf(stderr, "error message: line 3\n");
      return 1;
    }

Launch that app from Buck and verify that the output has been included in the exception message:

    [2016-10-03 14:47:11.600][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
    java.lang.RuntimeException: [/Users/plamenko/temp/exit_code_1.o, --version] finished with unexpected result:
    exit code: 1
    stdout:
    out message: line 1

    stderr:
    error message: line 1
    error message: line 2
    error message: line 3

      at com.facebook.buck.cxx.CxxToolProvider.getTypeFromPath(CxxToolProvider.java:138)
      at com.facebook.buck.cxx.CxxToolProvider.<init>(CxxToolProvider.java:110)
      at com.facebook.buck.cxx.PreprocessorProvider.<init>(PreprocessorProvider.java:30)
      at com.facebook.buck.cxx.DefaultCxxPlatforms.build(DefaultCxxPlatforms.java:104)
      at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:405)
      at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:242)
      at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:43)
      at com.facebook.buck.rules.Cell.<init>(Cell.java:115)
      at com.facebook.buck.rules.Cell.createRootCell(Cell.java:159)
      at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:905)
      at com.facebook.buck.cli.Main.runMainThenExit(Main.java:664)
      at com.facebook.buck.cli.Main.main(Main.java:1880)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)

And with truncating (for test set to first 10 and last 20 chars, for real first 10k and last 10k is used):

    [2016-10-04 17:57:42.856][error][command:null][tid:01][com.facebook.buck.cli.Main] Uncaught exception at top level
    java.lang.RuntimeException: [/Users/plamenko/temp/exit_code_1.o, --version] finished with unexpected result:
    exit code: 1
    stdout:
    out message: line 1

    stderr:
    error mess...
    <truncated>
    ...ror message: line 3

      at com.facebook.buck.cxx.CxxToolProvider.getTypeFromPath(CxxToolProvider.java:137)
      at com.facebook.buck.cxx.CxxToolProvider.access$2(CxxToolProvider.java:113)
      ...

Reviewed By: Coneko

fbshipit-source-id: 56f8a33