Attempt at fixing the flaky AndroidXmlFileIntegrationTest.
Summary:
`AndroidXmlFileIntegrationTest` fails once in a while with this stack trace:
```
FAIL  20.0s  4 Passed   1 Failed   com.facebook.buck.android.AndroidXmlFileIntegrationTest
FAILURE testRenamingAStringBuildsAllRules: There was no build log entry for target //java/com/sample/lib:lib
java.lang.AssertionError: There was no build log entry for target //java/com/sample/lib:lib
        at org.junit.Assert.fail(Assert.java:88)
        at com.facebook.buck.testutil.integration.BuckBuildLog.getLogEntryOrFail(BuckBuildLog.java:132)
        at com.facebook.buck.testutil.integration.BuckBuildLog.assertTargetBuiltLocally(BuckBuildLog.java:69)
        at com.facebook.buck.android.AndroidXmlFileIntegrationTest.testRenamingAStringBuildsAllRules(AndroidXmlFileIntegrationTest.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.facebook.buck.junit.BuckBlockJUnit4ClassRunner$SameThreadFailOnTimeout$1.call(BuckBlockJUnit4ClassRunner.java:118)
        at com.facebook.buck.junit.BuckBlockJUnit4ClassRunner$SameThreadFailOnTimeout$1.call(BuckBlockJUnit4ClassRunner.java:114)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

====STANDARD ERR====
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

I believe this is because `JavaUtilsLoggingBuildListener` doesn't flush
the log contents. This diff changes that.

Test Plan:
Run `buck clean && buck test --all` a bunch of times and verify the test
never fails.