Unwrap underlying root causes to make error messages usable.
Summary:
In order to use stream transformations with caches we have to
resort to `getUnchecked` method that wraps all exceptions into `UncheckedExecutionException`
and pollutes stack trace with useless noise making it hard to understand what
the actual problem is. This change extracts and propagates root causes instead.

Test Plan:
CI
```
# modify java_rules.bzl to introduce a syntax error
$ ./bin/buck build buck
ERROR: /Users/ttsugrii/local/buck/tools/build_rules/java_rules.bzl:5:1: syntax error at 'def': expected ,
BUILD FAILED: Cannot parse extension file //tools/build_rules:java_rules.bzl
```

Reviewed By: philipjameson

fbshipit-source-id: b9eb37b