Add tests that would have caught regression in TargetsCommand
Summary:
A recent diff caused a regression in `TargetsCommand` where
calling it with `--referenced_file path/to/foo.m` did not include
`AppleLibrary` rules and friends.

This adds a test that reproduces the regression in the recent diff.
The test now passes since that diff was reverted.

Test Plan:
Locally re-applied diff that caused regression.
Ran `ant java-test -Dtest.class=TargetsCommandTest`:

    [junit] Testcase: testGetMatchingAppleLibraryBuildTarget took 0.036 sec
    [junit]           FAILED
    [junit] expected:<[//foo:lib]> but was:<[]>
    [junit] junit.framework.AssertionFailedError: expected:<[//foo:lib]> but was:<[]>
    [junit]                                       at com.facebook.buck.cli.TargetsCommandTest.testGetMatchingAppleLibraryBuildTarget(TargetsCommandTest.java:496)
    [junit]
    [junit] Testcase: testGetMatchingAppleTestBuildTarget took 0.031 sec
    [junit]           FAILED
    [junit] expected:<[//foo:lib, //foo:testlib, //foo:xctest, //foo:test]> but was:<[]>
    [junit] junit.framework.AssertionFailedError: expected:<[//foo:lib, //foo:testlib, //foo:xctest, //foo:test]> but was:<[]>
    [junit]                                       at com.facebook.buck.cli.TargetsCommandTest.testGetMatchingAppleTestBuildTarget(TargetsCommandTest.java:559)

Reverted diff, re-ran `ant java-test -Dtest.class=TargetsCommandTest`:

    [junit] Testcase: testGetMatchingAppleLibraryBuildTarget took 0.036 sec
    [junit] Testcase: testGetMatchingAppleTestBuildTarget took 0.019 sec

Also ran `buck test -f TargetsCommandTest#.*Apple.*`:

  % buck test -f TargetsCommandTest#.*Apple.*
  Using buckd.
  [-] PROCESSING BUCK FILES...FINISHED 1.7s
  [-] BUILDING...FINISHED 38.3s
  Log:
  No Android platform target specified. Using default: Google Inc.:Google APIs:19
  TESTING SELECTED TESTS
  PASS     595ms  1 Passed   0 Skipped   0 Failed   //src/com/facebook/buck/util:one_project_filesystem_test
  PASS    <100ms 16 Passed   0 Skipped   0 Failed   //src/com/facebook/buck/apple:asset_catalogs_test
  PASS    <100ms 17 Passed   0 Skipped   0 Failed   //src/com/facebook/buck/parser:buck_test
  PASS      2.3s  2 Passed   0 Skipped   0 Failed   com.facebook.buck.cli.TargetsCommandTest
  PASS     17.4s  1 Passed   0 Skipped   0 Failed   //test/com/facebook/buck/cli/bootstrapper:bootstrapper
  TESTS PASSED