Downgrade errors in `outputTrace()` to warnings.
Summary:
If `BuckEventListener.outputTrace()` throws any exception after a build,
we normally catch the `Throwable` in `runMainThenExit()`, and exit with
the default exit code, which is 1 (failure).

This diff introduces `NonFatalHumanReadableException` which can be used
to re-throw an exception that can probably be ignored.  In this case,
when `ScubaEventListener`'s HTTP POST fails, we don't fail the whole
build and instead just print a stack trace and move on.

Test Plan:
Force a failure:

```
lang=none
$ buck build src/com/facebook/buck/debug/
BUILD SUCCESSFUL
[...]
Skipping over non-fatal error:
com.facebook.buck.cli.NonFatalHumanReadableException: Failed to log build Ijwxm44T's trace to Scuba
        at com.facebook.buck.event.listener.ScubaBuildListener.outputTrace(ScubaBuildListener.java:240)
        at com.facebook.buck.cli.Main.executeCommand(Main.java:501)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:354)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:690)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:705)
        at com.facebook.buck.cli.Main.main(Main.java:716)
Caused by: java.io.IOException: LOL
        at com.facebook.buck.event.listener.ScubaBuildListener.outputTrace(ScubaBuildListener.java:236)
        ... 5 more

$ echo $?
0
```