Fix cases where integer is returned
Summary:
main() in the wrapper was supposed to return callables to facilitate buck fix and buck run refactoring. Some places were missed (notably `buck kill`), and still returned an integer. Follow up work is probably to type this code so that this would have been caught.

Original error follows:
```
$ NO_BUCKD=1 ./buck.pex killall
'int' object has no attribute 'exit_code'
Traceback (most recent call last):
  File "programs/buck.py", line 255, in <module>
    exit_code = exit_code_callable.exit_code
AttributeError: 'int' object has no attribute 'exit_code'
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 328, in execute
  File ".bootstrap/_pex/pex.py", line 261, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 371, in _execute
  File ".bootstrap/_pex/pex.py", line 429, in execute_entry
  File ".bootstrap/_pex/pex.py", line 434, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "programs/buck.py", line 303, in <module>
    exit_code = exit_code_callable()
TypeError: 'int' object is not callable
```

Reviewed By: rajyengi

shipit-source-id: 8801ad38f7