Throw an exception when creating AndroidNdk
Summary:
`DefaultAndroidDirectoryResolver` contains some logic that provides nice explanation why Android NDK/SDK cannot be resolved. After recent move to the toolchain framework that logic wasn't used.

This change brings back showing an error that explains why Android NDK is not recognized.

Test Plan:
Message before this change:

```
$ ANDROID_NDK_REPOSITORY="/12321" buck build //some/android/target
...
UNKNOWN ERROR: com.facebook.buck.util.HumanReadableException: Unknown toolchain: android-ndk-location
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.util.HumanReadableException: Unknown toolchain: android-ndk-location
```

After:

```
UNKNOWN ERROR: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_NDK_REPOSITORY' points to an invalid directory '/12321'.
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_NDK_REPOSITORY' points to an invalid directory '/12321'.
```

Reviewed By: ttsugriy

fbshipit-source-id: 2b8894b