Fix artifacts downloading on Windows
Summary: `buck build buck` fails on Windows when unpacking artifacts because ZIP files have paths with forward slashes.

Test Plan:
Before:
```
PS C:\open\buck> ant clean default
PS C:\open\buck> .\bin\buck.ps1 kill
PS C:\open\buck> .\bin\buck.ps1 clean
PS C:\open\buck> .\bin\buck.ps1 build buck -c cache.http_mode=readwrite
PARSING BUCK FILES: FINISHED IN 0.1s
CREATING ACTION GRAPH: FINISHED IN 0.0s
Buck encountered an internal error
java.lang.IllegalStateException: Artifact missing artifactMetadata for key RECORDED_PATHS
        at com.google.common.base.Preconditions.checkState(Preconditions.java:582)
        at com.facebook.buck.rules.DefaultOnDiskBuildInfo.validateArtifactHasKey(DefaultOnDiskBuildInfo.java:249)
        at com.facebook.buck.rules.DefaultOnDiskBuildInfo.validateArtifact(DefaultOnDiskBuildInfo.java:244)
        at com.facebook.buck.rules.CachingBuildRuleBuilder.unzipArtifactFromCacheResult(CachingBuildRuleBuilder.java:1227)
        at com.facebook.buck.rules.CachingBuildRuleBuilder.lambda$27(CachingBuildRuleBuilder.java:1128)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1016)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:867)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:691)
        at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:240)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:162)
        ... 10 more

    When building rule //programs:gen_build_type_info.
DOWNLOADED 77 ARTIFACTS, 624.00 KBYTES
BUILDING: FINISHED IN 3.1s (100%) 15/91 JOBS, 1 UPDATED, 1.1% CACHE MISS
BUILD FAILED
```

After:
```
PS C:\open\buck> ant clean default
PS C:\open\buck> .\bin\buck.ps1 kill
PS C:\open\buck> .\bin\buck.ps1 clean
PS C:\open\buck> .\bin\buck.ps1 build buck -c cache.http_mode=readwrite
...
BUILT 1363/1363 JOBS 22.0s //programs:buck
DOWNLOADED 2515 ARTIFACTS, 19.65 MBYTES
BUILDING: FINISHED IN 6m 26.4s (100%) 1363/1363 JOBS, 1363 UPDATED, 98.2% CACHE MISS
WAITING FOR HTTP CACHE UPLOADS 310.71 MBYTES (1492 COMPLETE/0 FAILED/2 UPLOADING/0 PENDING)
BUILD SUCCEEDED
HTTP CACHE UPLOAD: FINISHED 401.08 MBYTES (1494 COMPLETE/0 FAILED/0 UPLOADING/0 PENDING)
PS C:\open\buck> .\bin\buck.ps1 kill
PS C:\open\buck> .\bin\buck.ps1 clean
PS C:\open\buck> .\bin\buck.ps1 build buck
PARSING BUCK FILES... 3.3s (100%)
CREATING ACTION GRAPH: FINISHED IN 1.4s
BUILT 1/1363 JOBS 0.4s //third-party/nailgun:ng
BUILT 2/1363 JOBS 0.5s //programs:subprocutils
BUILT 3/1363 JOBS 0.2s //programs:buck_version
BUILT 4/1363 JOBS 0.4s //config:logging.properties
BUILT 5/1362 JOBS 0.4s //third-party/py/pex:pex
BUILT 6/1362 JOBS 0.5s //src/com/facebook/buck/shell:sh_binary_template
BUILT 7/1362 JOBS 0.5s //programs/fixes/source_only_abi:fix-lib
BUILT 8/1362 JOBS 0.6s //third-party/py/pathlib:pathlib.py
BUILT 9/1362 JOBS 0.3s //assets/android:agent.apk
BUILT 10/1362 JOBS 0.4s //third-party/java/ObjCBridge:libjcocoa.dylib
BUILT 11/1362 JOBS 0.5s //third-party/java/dx:etc_dx
BUILT 13/1360 JOBS 0.4s //assets/android:native-exopackage-fakes.apk
BUILT 35/35 JOBS 0.0s //programs:bucklib
DOWNLOADED 33 ARTIFACTS, 189.03 MBYTES
BUILDING: FINISHED IN 14.7s (100%) 35/35 JOBS, 35 UPDATED, 0.0% CACHE MISS
BUILD SUCCEEDED
```

Reviewed By: styurin

fbshipit-source-id: 0823411