TestCompiler: Show error messages when compilation fails
Summary: Previously it would just fail, and you'd have to dig in with a debugger to figure out why.

Test Plan:
Change a test so that code being compiled with TestCompiler has a syntax error. Verify
a nice neat error message is provided, for example:

```
java.lang.AssertionError: Compilation failed! Diagnostics:
/var/folders/6l/vnx69_dd2n350z3r19crkh8wtgfqms/T/junit9027585281430870503/A.java:3: error: ';' expected
  B.C field
           ^
```

Reviewed By: asp2insp

fbshipit-source-id: ec30696