Add missing lock.
Summary:
```
    [javac] src/com/facebook/buck/event/listener/SuperConsoleEventBusListener.java:663: error: [GuardedBy] This access should be guarded by 'this.distBuildStatusLock', which is not currently held
    [javac]         String.format("local status: %s%s", stampedeLocalBuildStatus, localBuildProgessString);
    [javac]                                             ^
    [javac]     (see http://errorprone.info/bugpattern/GuardedBy)
    [javac] 1 error
```

Test Plan: CI

Reviewed By: styurin

fbshipit-source-id: ce0516e