fix depfile matching on windows RE
Summary:
I noticed that some of the binaries built with clang on windows RE fail with

```
java.nio.file.NoSuchFileException: K:\work\arvr\tools\buck\sanitize-blacklist.txt
```

Turned out this happens because clang apparently emits files with "\\" in them.
Let's replace them with a single "\"

Reviewed By: KapJI

fbshipit-source-id: 8289bceb9c195c7ddb9dbfeb4c43061fe3b8eb25