Fix error-prone error
Summary:
The version of guava buck is using has an annotation to verify that the
result is used, so following error happens at compile time:
```
ERROR: ~/local/buck/src/com/facebook/buck/rules/BUILD:354:1: Building src/com/facebook/buck/rules/librules.jar (40 source files) failed: Worker process sent response with exit code: 1.
warning: Annotation Value.Parameter is superfluous when Style(allParameters = true)
src/com/facebook/buck/rules/CachingBuildEngine.java:1480: error: [CheckReturnValue] Ignored return value of method that is annotated with CheckReturnValue
        HashCode.fromString(ruleKeyValue);
                           ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?
Target //src/com/facebook/buck/jvm/java:rules failed to build
```
Fix extracts verification method into a separate method to make its intent clear and suppress
unnecessary check.

Test Plan: buck test ...

Reviewed By: dinhviethoa

fbshipit-source-id: 3225169