Fix message formatting in Starlark embedding
Summary:
`BuildFileParseException.createForUnknownParseError` failed if there's percent in error message, because `createForUnknownParseError` invokes `String.format`.

Fix this error:

```
Buck encountered an internal error
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags = (
	at com.facebook.buck.parser.TargetSpecResolver.collectTargets(TargetSpecResolver.java:444)
	at com.facebook.buck.parser.TargetSpecResolver.resolveSpecsGeneric(TargetSpecResolver.java:318)
	at com.facebook.buck.parser.TargetSpecResolver.resolveTargetSpecsUnconfigured(TargetSpecResolver.java:268)
	at com.facebook.buck.parser.ParserWithConfigurableAttributes.resolveTargetSpecsUnconfigured(ParserWithConfigurableAttributes.java:418)
	at com.facebook.buck.cli.UnconfiguredQueryTargetEvaluator.resolveBuildTargetPatterns(UnconfiguredQueryTargetEvaluator.java:117)
	at com.facebook.buck.cli.AbstractQueryPatternEvaluator.resolveTargetPatterns(AbstractQueryPatternEvaluator.java:110)
	at com.facebook.buck.cli.UnconfiguredQueryTargetEvaluator.evaluateTarget(UnconfiguredQueryTargetEvaluator.java:94)
	at com.facebook.buck.cli.UnconfiguredQueryEnvironment.preloadTargetPatterns(UnconfiguredQueryEnvironment.java:156)
	at com.facebook.buck.cli.AbstractQueryCommand.runMultipleQuery(AbstractQueryCommand.java:215)
	at com.facebook.buck.cli.AbstractQueryCommand.formatAndRunQuery(AbstractQueryCommand.java:174)
	at com.facebook.buck.cli.UnconfiguredQueryCommand.runWithoutHelp(UnconfiguredQueryCommand.java:92)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:272)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:92)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1573)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:547)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
Caused by: java.util.concurrent.ExecutionException: java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags = (
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:487)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.facebook.buck.parser.TargetSpecResolver.collectTargets(TargetSpecResolver.java:438)
	... 21 more
Caused by: java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags = (
	at java.base/java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4422)
	at java.base/java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3151)
	at java.base/java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3109)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2870)
	at java.base/java.util.Formatter.parse(Formatter.java:2713)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.facebook.buck.parser.exceptions.BuildFileParseException.createForUnknownParseError(BuildFileParseException.java:76)
	at com.facebook.buck.skylark.parser.AbstractSkylarkFileParser.exec(AbstractSkylarkFileParser.java:268)
	at com.facebook.buck.skylark.parser.AbstractSkylarkFileParser.parse(AbstractSkylarkFileParser.java:244)
	at com.facebook.buck.skylark.parser.SkylarkProjectBuildFileParser.getManifest(SkylarkProjectBuildFileParser.java:142)
	at com.facebook.buck.skylark.parser.SkylarkProjectBuildFileParser.getManifest(SkylarkProjectBuildFileParser.java:60)
	at com.facebook.buck.parser.HybridProjectBuildFileParser.getManifest(HybridProjectBuildFileParser.java:69)
	at com.facebook.buck.parser.HybridProjectBuildFileParser.getManifest(HybridProjectBuildFileParser.java:49)
	at com.facebook.buck.json.TargetCountVerificationParserDecorator.getManifest(TargetCountVerificationParserDecorator.java:74)
	at com.facebook.buck.json.TargetCountVerificationParserDecorator.getManifest(TargetCountVerificationParserDecorator.java:34)
	at com.facebook.buck.parser.decorators.EventReportingProjectBuildFileParser.getManifest(EventReportingProjectBuildFileParser.java:69)
	at com.facebook.buck.parser.decorators.EventReportingProjectBuildFileParser.getManifest(EventReportingProjectBuildFileParser.java:38)
	at com.facebook.buck.parser.FileParserPool.lambda$getManifest$0(FileParserPool.java:83)
	at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:136)
	at com.facebook.buck.util.concurrent.ResourcePool$1.apply(ResourcePool.java:128)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:210)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:199)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Reviewed By: bobyangyf

fbshipit-source-id: f1c1a74d7d3794475b0e133b22de0ad94f9481e4