Plumb import_paths param through to gen_aidl
Summary:
Problem:
Targeting SDK 33 and updating the aidl tool to the v33 version yields some changes from Google's end.

One of these appears to affect import path discovery, making it more restrictive. This appears to require more explict paths to provided to the aidl tool.

Example:
Each of these examples is the raw call made to aidl, this would be what the buck step generates in the end to actually perform the aidl generation.

SDK 31 tooling:
```
/opt/android/sdk_D37111790/build-tools/31.0.0/aidl -p/opt/android/sdk_D37111790/platforms/android-31/framework.aidl -I/data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl -o/data/sandcastle/boxes/fbsource/buck-out/bin/fe3a39b8/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/__ISmartCameraInternalControlService.aidl fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlService.aidl
```

-Success

SDK 33 Tooling:
```
/opt/android/sdk_D37111790/build-tools/33.0.0/aidl -p/opt/android/sdk_D37111790/platforms/android-33/framework.aidl -I/data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl -o/data/sandcastle/boxes/fbsource/buck-out/bin/fe3a39b8/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/__ISmartCameraInternalControlService.aidl fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlService.aidl
```

-Failure
```
ERROR: /data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlConnection.aidl:29.1-26: Failed to resolve 'IInternalControlSession'
ERROR: /data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlConnection.aidl:29.45-67: Failed to resolve 'IControlStateCallback'
ERROR: /data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlConnection.aidl:37.42-64: Failed to resolve 'IAvailabilityListener'
ERROR: /data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlConnection.aidl:42.41-63: Failed to resolve 'IAvailabilityListener'
ERROR: /data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlConnection.aidl:56.18-30: Failed to resolve 'ModeSetting'
ERROR: /data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlConnection.aidl:74.31-55: Failed to resolve 'SessionPropertiesBundle'
```

These errors can be observed in D37694695 which attempts to update the build tooling to SDK 33.

If we add the additional "third-party" import path to the SDK 33 command:
```
/opt/android/sdk_D37111790/build-tools/33.0.0/aidl -p/opt/android/sdk_D37111790/platforms/android-33/framework.aidl -I/data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl -I/data/sandcastle/boxes/fbsource/fbandroid/first-party/portal-sdk/third-party/smartcamera-ipc/src/main/aidl -o/data/sandcastle/boxes/fbsource/buck-out/bin/fe3a39b8/fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/__ISmartCameraInternalControlService.aidl fbandroid/first-party/portal-sdk/first-party/smartcamera-ipc/src/main/aidl/com/facebook/portal/smartcamera/internal/control/ISmartCameraInternalControlService.aidl
```
-Success

The proposed change would add an optional 'import_paths' param to the gen_fbandroid_aidl and native.gen_aidl methods. This would take a set of paths that would share the same format as those provided to 'import_path' and would be concatenated together to form a list of combinedImportPaths passed to the aidl command.

The AidlStep (and aidl tool) already supports multiple import paths, this mainly just wires up the plumbing to optionally supply more import paths if desired.

Couple of notes:
I added this as an optional param since it'll require less adjustment of other locations and since we appear to use the import_path as an output location it seemed safer to just leave that untouched.

Reviewed By: IanChilds

fbshipit-source-id: 8443bcd38e8ec85bc912a94eae4d2ba34902ea73