Add more dependencies to PackageStringAssets rule
Summary: `PackageStringAssets` accesses android resources, but it doesn't depend on targets that produce these resources. This diff adds required dependencies to this rule.

Test Plan:- Remove the output of some genrule that produces `res` directory of an `android_resource` target.
- `buck build android_binary#package_string_assets` should fail with:

    Error parsing string file for locale: ru
    java.nio.file.NoSuchFileException: /.../buck-out/gen/android_res/.../res/values-ru/strings.xml
    java.nio.file.NoSuchFileException: /.../buck-out/gen/android_res/.../res/values-ru/strings.xml
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
    at java.nio.file.Files.newInputStream(Files.java:152)
    at com.facebook.buck.util.XmlDomParser.parse(XmlDomParser.java:39)
    at com.facebook.buck.android.CompileStringsStep.compileStringFiles(CompileStringsStep.java:297)
    at com.facebook.buck.android.CompileStringsStep.execute(CompileStringsStep.java:160)
   ...

Apply the patch and do that same commands, the build should finish fine.

Reviewed By: Coneko

fb-gh-sync-id: e720d88
shipit-source-id: e720d88