Improve compilation error output.
Summary:
Right now, on compilation error, we print the output of the javac command
followed by the entire javac command itself, which can be very long (usually
a long list of classpath entries) and more importantly in most cases irrelevant
to a developer. You end up scrolling a bunch to get to the actual javac
command output, which sucks.

This change makes it so that we print the entire command only if the verbosity
is `>= COMMANDS` and otherwise just prints the command name.

Test Plan:
Introduce a compilation error in one of the .java files in instagram.

Without this change:
```
Log:
/home/natthu/fbandroid/java/com/instagram/cache/base/CacheUtil.java:14: error: cannot find symbol
if (!pat.exists()) {
  ^
    symbol:   variable pat
    location: class com.instagram.cache.base.CacheUtil
    Note: /home/natthu/fbandroid/java/com/instagram/cache/base/CacheUtil.java uses or overrides a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Errors: 1. Warnings: 0.
BUILD FAILED: //java/com/instagram/cache/base:base failed with exit code 1:
javac -target 6 -source 6 -g -bootclasspath /home/natthu/AndroidSDK/platforms/android-19/android.jar:/home/natthu/AndroidSDK/add-ons/addon-google_apis-google-19/libs/effects.jar:/home/natthu/AndroidSDK/add-ons/addon-google_apis-google-19/libs/maps.jar:/home/natthu/AndroidSDK/add-ons/addon-google_apis-google-19/libs/usb.jar -processorpath /home/natthu/devtools/buck/build/abi_processor/classes -processor com.facebook.buck.java.abi.AbiWriter -Abuck.output_abi_file=/home/natthu/fbandroid/./buck-out/gen/java/com/instagram/cache/base/lib__base__abi/abi -d /home/natthu/fbandroid/buck-out/bin/java/com/instagram/cache/base/lib__base__classes -classpath /home/natthu/fbandroid/third-party/java/android/httpclientandroidlib/httpclientandroidlib-1.0.3.jar:/home/natthu/fbandroid/third-party/java/jsr-305/jsr305.jar @buck-out/gen/java/com/instagram/cache/base/__base__srcs
```

With this change:
```
Log:
/home/natthu/fbandroid/java/com/instagram/cache/base/CacheUtil.java:14: error: cannot find symbol
if (!pat.exists()) {
  ^
    symbol:   variable pat
    location: class com.instagram.cache.base.CacheUtil
    Note: /home/natthu/fbandroid/java/com/instagram/cache/base/CacheUtil.java uses or overrides a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Errors: 1. Warnings: 0.
BUILD FAILED: //java/com/instagram/cache/base:base failed with exit code 1:
javac
```