Fix invalid -include path for system frameworks
Summary:
When including a system framework such as:
```
-include Foundation/Foundation.h
```
`buck project` will translate that include into a full absolute path by prefixing repo root path such as:
```
-include $REPO_ROOT/Foundation/Foundation.h
```
which leads to indexing and compile issues since the absolute path does not exist. We should not prefix these system framework includes with repo root path, since system framework include paths will already exist by default in Xcode's clang commands.
Example clang indexing {F743471838} error
```
error: '/Users/tjwo/fbsource/Foundation/Foundation.h' file not found
```

fbshipit-source-id: cebdea654f799a8b5f5a202920b84ca77467d479