javacd startup command: change an order of arguments
Summary:
Windows java implementation requires to specify jar argument with main class before other arguments.

Fail:
```
PS C:\Program Files\Java\jdk1.8.0_241\bin> .\java.exe -Dfile.encoding=UTF-8 -jar C:\open\directory\buck-out\tmp\resources\ee6fe65c095d04bcc53ae90a8c4e087f\javacd
>>
Error: Could not find or load main class .encoding=UTF-8
```

Works:
```
PS C:\Program Files\Java\jdk1.8.0_241\bin> .\java.exe  -jar C:\open\directory\buck-out\tmp\resources\ee6fe65c095d04bcc53ae90a8c4e087f\javacd -Dfile.encoding=UTF-8
>>
Exception in thread "main" java.lang.NullPointerException: Missing env var: BUCK_VERBOSITY
        at java.util.Objects.requireNonNull(Objects.java:290)
        at com.facebook.buck.jvm.java.stepsbuilder.javacd.main.WorkerToolParsedEnvs.getNonNullValue(WorkerToolParsedEnvs.java:57)
        at com.facebook.buck.jvm.java.stepsbuilder.javacd.main.WorkerToolParsedEnvs.parse(WorkerToolParsedEnvs.java:48)
        at com.facebook.buck.jvm.java.stepsbuilder.javacd.main.JavaCDWorkerToolMain.main(JavaCDWorkerToolMain.java:67)
```

 ---

**This change allows javacd to work on Windows!**
yeah_happy

Reviewed By: stepancheg

fbshipit-source-id: 7e6bed47dd26686dc14ccfc5c4a7755f10c5b227