Add `--ignore-when-dependencies-fail` to buck test
Summary:
This uses the `TestResultsGrouper` in `TestCommand` and `buck test` so
that tests with broken dependencies have their output suppressed when
using `--ignore-when-dependencies-fail` (aliased to `-i`).

This is useful if you have a set of almost-unit-tests that have implied
dependencies between them.  The example in the documentation shows
`Bricks` and `BricksTest`, with `Bricks` being used by `HouseBuilder`,
which in turn is tested by `HouseBuilderTest`.  If `Bricks`'s
constructor is broken then both tests will fail with the same stack
trace.

```
PASS <100ms  1 Passed   0 Failed   com.example.construction.MortarTest
FAIL <100ms  0 Passed   1 Failed   com.example.construction.HouseBuilderTest
FAILURE shouldUseBricks: could not construct a "Bricks"!
java.lang.RuntimeException: could not construct a "Bricks"!
        at com.example.construction...
FAIL <100ms  0 Passed   1 Failed   com.example.construction.BricksTest
FAILURE shouldConstruct: could not construct a "Bricks"!
java.lang.RuntimeException: could not construct a "Bricks"!
        at com.example.construction...
```

If `--ignore-when-dependencies-fail` is given however, only the output
from `BricksTest` is shown, and the output from `HouseBuilderTest` is
suppressed and the result is shown as `DROP`:

```
PASS <100ms  1 Passed   0 Failed   com.example.construction.MortarTest
DROP <100ms  0 Passed   1 Failed   com.example.construction.HouseBuilderTest
FAIL <100ms  0 Passed   1 Failed   com.example.construction.BricksTest
FAILURE shouldConstruct: could not construct a "Bricks"!
java.lang.RuntimeException: could not construct a "Bricks"!
        at com.example.construction...
```

Test Plan: None, integration test to come in a separate diff.