Don't recursively copy or link dependencies of genrules in Apple project generation
Summary:
Previously, `AppleBuildRules.getRecursiveTargetNodeDependenciesOfType()`
would go through all recursive dependencies of a rule (stopping at bundles) when
determining what to link or copy into a rule.

This meant even dependencies of `genrule` executed as part of a build
were being linked or copied into rules that depended on the genrule.

When I enabled building `xctool` from a `genrule` in my previous diff
`[apple test] Support building xctool from source`, that meant any
`apple_test` rule (or dependency thereof) would automatically link in
all of the libraries used to link `xctool`! Not what we want.

This fixes the bug by ensuring we explicitly stop at `genrule`s when
linking or copying deps.

Test Plan:
Added new unit tests. Before test, confirmed new tests failed:

    Testsuite: com.facebook.buck.apple.AppleBuildRulesTest
    Testcase: testIosResourceIsNotXcodeTargetBuildRuleType took 0.069 sec
    Testcase: testAppleLibraryIsXcodeTargetBuildRuleType took 0 sec
    Testcase: exportedDepsAreCollectedForCopying took 0.219 sec
    Testcase: copyingStopsAtGenruleDep took 0.021 sec
              FAILED
    expected:<[//foo:genrule]> but was:<[//foo:genrule, //foo:lib]>
    junit.framework.AssertionFailedError: expected:<[//foo:genrule]> but was:<[//foo:genrule, //foo:lib]>
                                          at com.facebook.buck.apple.AppleBuildRulesTest.copyingStopsAtGenruleDep(AppleBuildRulesTest.java:377)

    Testcase: testAppleLibraryIsNotXcodeTargetTestBuildRuleType took 0.021 sec
    Testcase: testAppleTestIsXcodeTargetTestBuildRuleType took 0.036 sec
    Testcase: testOctestIsTestBundleExtension took 0 sec
    Testcase: testXctestIsTestBundleExtension took 0 sec
    Testcase: exportedDepsOfDylibsAreCollectedForLinking took 0.008 sec
    Testcase: linkingStopsAtGenruleDep took 0.006 sec
              FAILED
    expected:<[//foo:genrule]> but was:<[//foo:genrule, //foo:lib]>
    junit.framework.AssertionFailedError: expected:<[//foo:genrule]> but was:<[//foo:genrule, //foo:lib]>
                                          at com.facebook.buck.apple.AppleBuildRulesTest.linkingStopsAtGenruleDep(AppleBuildRulesTest.java:321)

    Testcase: testRecursiveTargetsIncludesBundleBinaryFromOutsideBundle took 0.005 sec

Applied fix, confirmed new tests passed.