Do not hang when jdk is not found
Summary:
When building buck when JDK is not found, but JRE is present, build properly returns error, but hangs for a couple of minutes.

This diff fixed the issue. It simply makes code safer: if future is not initialized, it is initialized with default value, so `.get` won't hang.

This change is safe, because `.set` is no-op if future is initialized (even if initialized with future).

Test Plan:
Without this patch `buck build buck` results in:

```
...
Build failed: No system compiler found. Did you install the JRE instead of the JDK?
    When running <source_abi>.
    When building rule //src/com/facebook/buck/util:constants#source-abi.
DOWNLOADED 1256 ARTIFACTS, 9.81 MBYTES
BUILDING: FINISHED IN 1m 5.9s (100%) 84/1200 JOBS, 24 UPDATED, 2.0% CACHE MISS
BUILD FAILED
UNKNOWN ERROR: Shutdown timed out for thread pool Build
  Thread Path cache cleanup:
    java.lang.Object.wait(Native Method)
    java.lang.ref.ReferenceQueue.remove(Unknown Source)
    java.lang.ref.ReferenceQueue.remove(Unknown Source)
    com.google.devtools.build.lib.vfs.Path$1.run(Path.java:131)
  Thread Build-2:
    sun.misc.Unsafe.park(Native Method)
    java.util.concurrent.locks.LockSupport.park(Unknown Source)
    com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:497)
    com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
    com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.close(Jsr199JavacInvocation.java:385)
    com.facebook.buck.jvm.java.Jsr199JavacInvocation.close(Jsr199JavacInvocation.java:180)
    com.facebook.buck.jvm.java.JavacPipelineState.close(JavacPipelineState.java:165)
    com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipeline.run(BuildRulePipelinesRunner.java:175)
    com.facebook.buck.rules.BuildRulePipelinesRunner$1.run(BuildRulePipelinesRunner.java:112)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$6(WeightedListeningExecutorService.java:104)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$386/1835316563.call(Unknown Source)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$4(WeightedListeningExecutorService.java:78)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$387/1399225534.apply(Unknown Source)
    com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
    com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
    com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
    com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
    java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.lang.Thread.run(Unknown Source)
java.lang.RuntimeException: Shutdown timed out for thread pool Build
  Thread Path cache cleanup:
    java.lang.Object.wait(Native Method)
    java.lang.ref.ReferenceQueue.remove(Unknown Source)
    java.lang.ref.ReferenceQueue.remove(Unknown Source)
    com.google.devtools.build.lib.vfs.Path$1.run(Path.java:131)
  Thread Build-2:
    sun.misc.Unsafe.park(Native Method)
    java.util.concurrent.locks.LockSupport.park(Unknown Source)
    com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:497)
    com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
    com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.close(Jsr199JavacInvocation.java:385)
    com.facebook.buck.jvm.java.Jsr199JavacInvocation.close(Jsr199JavacInvocation.java:180)
    com.facebook.buck.jvm.java.JavacPipelineState.close(JavacPipelineState.java:165)
    com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipeline.run(BuildRulePipelinesRunner.java:175)
    com.facebook.buck.rules.BuildRulePipelinesRunner$1.run(BuildRulePipelinesRunner.java:112)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$6(WeightedListeningExecutorService.java:104)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$386/1835316563.call(Unknown Source)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$4(WeightedListeningExecutorService.java:78)
    com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$387/1399225534.apply(Unknown Source)
    com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
    com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
    com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
    com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
    java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.lang.Thread.run(Unknown Source)
        at com.facebook.buck.cli.CommandThreadManager.close(CommandThreadManager.java:153)
        at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:387)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:231)
        at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1110)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:424)
        at com.facebook.buck.cli.Main.main(Main.java:1868)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)
```

Note that there's a couple of minutes delay between `BUILD FAILED` message and `UNKNOWN ERROR` message.

With this patch (clean checkout of buck + changed `.buckversion`) result is:

```
Build failed: No system compiler found. Did you install the JRE instead of the JDK?
    When running <source_abi>.
    When building rule //src/com/facebook/buck/log/views:views#source-abi.
DOWNLOADED 1262 ARTIFACTS, 9.87 MBYTES
BUILDING: FINISHED IN 51.2s (100%) 61/1165 JOBS, 61 UPDATED, 3.8% CACHE MISS
BUILD FAILED
```

(And build quickly finishes)

Reviewed By: philipjameson

fbshipit-source-id: cbf9896