Show an actual error with explanation when Android SDK cannot be located
Summary:
After the recent changes in toolchains in case when Android SDK configuration is invalid Buck showed non-user friendly message without any context about a problem:

```
UNKNOWN ERROR: com.facebook.buck.toolchain.ToolchainInstantiationException: Unknown toolchain: android-sdk-location
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.toolchain.ToolchainInstantiationException: Unknown toolchain: android-sdk-location
```

This change exposes the original error message about what's wrong with the configuration:

```
UNKNOWN ERROR: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_SDK' points to an invalid directory '/2222'.
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_SDK' points to an invalid directory '/2222'.
```

Test Plan: Try to build Android apps with broken and valid configuration, check the message.

Reviewed By: ttsugriy

fbshipit-source-id: 267cc01