Don't use stripped target as base target when creating an AppleDebuggableBinary
Summary:
When using buck targets for a apple bundle target with an embedded frameworks, we were hitting the following exception:

```
$ buck targets [target]#iphonesimulator-x86_64 --show-rulekey --show-transitive-rulekeys
Action graph will be rebuilt because files have been added or removed.
Parsing buck files: finished in 3.1 sec (100%)
Creating action graph: finished in 1.9 sec (100%)
[2017-10-13 16:47:17.626][error][command:null][tid:209][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: This function used to strip stripped, which masked errors in constructing build targets and caused the returned rule's build target to differ from the requested one. This is now explicitly disallowed to catch existing and future programming errors of this kind.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.facebook.buck.cxx.CxxStrip.removeStripStyleFlavorInTarget(CxxStrip.java:94)
	at com.facebook.buck.apple.AppleLibraryDescription.createLibraryBuildRule(AppleLibraryDescription.java:431)
	at com.facebook.buck.apple.AppleLibraryDescription.createBuildRule(AppleLibraryDescription.java:345)
	at com.facebook.buck.apple.AppleLibraryDescription.createBuildRule(AppleLibraryDescription.java:91)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:88)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.lambda$requireRule$0(SingleThreadedBuildRuleResolver.java:111)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.computeIfAbsent(SingleThreadedBuildRuleResolver.java:84)
	at com.facebook.buck.rules.SingleThreadedBuildRuleResolver.requireRule(SingleThreadedBuildRuleResolver.java:107)
	at com.facebook.buck.cli.TargetsCommand.computeShowRules(TargetsCommand.java:944)
	at com.facebook.buck.cli.TargetsCommand.runWithExecutor(TargetsCommand.java:404)
	at com.facebook.buck.cli.TargetsCommand.runWithoutHelp(TargetsCommand.java:354)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1129)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:406)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2001)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
```

The issue is that AppleDebuggableBinary should not be created with a stripped flavor.
This diff is clarifying related code and make sure we use a non-stripped flavored target tro create the AppleDebuggableBinary.

Test Plan:
CI + regression tests

Before diff: regression test fails
After diff: regression test succeeds

Reviewed By: ttsugriy

fbshipit-source-id: d5cfcb6