Change ArtifactUploader to use an ErrorLogger
Summary:
ArtifactUploader was doing it's own handling of logging exceptions,
ErrorLogger does this much better.

Old:
```
RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@7e657457 with executor MoreExecutors.directExecutor()
com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: java.nio.file.NoSuchFileException: /var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/buck_artifact_orca8876380901526410578.zip
	at com.facebook.buck.artifact_cache.ArtifactUploader$1.onCompletion(ArtifactUploader.java:93)
	at com.facebook.buck.artifact_cache.ArtifactUploader$1.onSuccess(ArtifactUploader.java:70)
	at com.facebook.buck.artifact_cache.ArtifactUploader$1.onSuccess(ArtifactUploader.java:67)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:41)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1135)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1073)
	at com.facebook.buck.artifact_cache.ArtifactUploader.performUploadToArtifactCache(ArtifactUploader.java:65)
	at com.facebook.buck.rules.BuildInfoRecorder.performUploadToArtifactCache(BuildInfoRecorder.java:287)
	at com.facebook.buck.rules.CachingBuildRuleBuilder.uploadToCache(CachingBuildRuleBuilder.java:662)
	at com.facebook.buck.rules.CachingBuildRuleBuilder.handleResult(CachingBuildRuleBuilder.java:709)
	at com.facebook.buck.rules.CachingBuildRuleBuilder.access$000(CachingBuildRuleBuilder.java:110)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$1.onSuccess(CachingBuildRuleBuilder.java:317)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$1.onSuccess(CachingBuildRuleBuilder.java:314)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onSuccess(MoreFutures.java:127)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:296)
	at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:983)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:41)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:50)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:551)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submitWithSemaphore(WeightedListeningExecutorService.java:74)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:102)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:91)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:97)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.execute(WeightedListeningExecutorService.java:154)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:118)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:296)
	at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:983)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:41)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:50)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:551)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submitWithSemaphore(WeightedListeningExecutorService.java:74)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:102)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:91)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:97)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.execute(WeightedListeningExecutorService.java:154)
	at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:983)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:118)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:711)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:296)
	at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:983)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:41)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:50)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:551)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submitWithSemaphore(WeightedListeningExecutorService.java:74)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:102)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:91)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.submit(WeightedListeningExecutorService.java:97)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.execute(WeightedListeningExecutorService.java:154)
	at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:983)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/buck_artifact_orca8876380901526410578.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.facebook.buck.util.NamedTemporaryFile.close(NamedTemporaryFile.java:41)
	at com.facebook.buck.artifact_cache.ArtifactUploader$1.onCompletion(ArtifactUploader.java:89)
	... 124 more
```
New:
```
Buck encountered an internal error
java.nio.file.NoSuchFileException: /var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/buck_artifact_orca4567059919246327029.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.facebook.buck.util.NamedTemporaryFile.close(NamedTemporaryFile.java:41)
	at com.facebook.buck.artifact_cache.ArtifactUploader$1.onCompletion(ArtifactUploader.java:88)
	... 112 more

    When deleting temporary zip /var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/buck_artifact_orca4567059919246327029.zip for upload of //src/com/facebook/orca:orca.
```

Test Plan: CI

Reviewed By: ttsugriy

fbshipit-source-id: 575b4dd