Revert "Allow usage of apple-asset-catalog flavor from the command line"
Summary:
This reverts commit f6bfaf2148c2b020bb0d92cdd9124a2ee4146066.

Causes issues with fbobjc version bump, builds are failing with:
java.lang.IllegalStateException: A build rule for this target has already been created: //Apps/MSQRD/Editor/VersionLauncher:VersionLauncher#apple-asset-catalog,macosx-x86_64

Reviewed By: jtorkkola

fbshipit-source-id: 5a1ce1493f