Report swallowed exceptions sent to Console to debug log
Summary:
We have a lot of code like the following (from `Build.java`):

    } catch (IOException e) {
      console.printBuildFailureWithoutStacktrace(e);
    } catch (StepFailedException e) {
      console.printBuildFailureWithoutStacktrace(e);
    } catch (ExecutionException e) {
      Throwable cause = e.getCause();
      if (cause instanceof HumanReadableException) {
        throw ((HumanReadableException) cause);
      } else if (cause instanceof ExceptionWithHumanReadableMessage) {
        throw new HumanReadableException((ExceptionWithHumanReadableMessage) cause);
      } else {
        if (cause instanceof RuntimeException) {
          console.printBuildFailureWithStacktrace(e);
        } else {
          console.printBuildFailureWithoutStacktrace(e);
        }
      }
    }

Whenever we swallow exceptions like this, it's difficult to diagnose
what went wrong looking at the debug logs.

This diff ensures we log exceptions or other build failures printed
to the console, so even if we swallow them the debug logs will
include the information shown to the user.

Test Plan:
buck build //path/to:apple_test_rule

Previously, it failed with:

  java.util.concurrent.ExecutionException: java.lang.NullPointerException
          at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
          at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
          at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
          at com.facebook.buck.command.Build.executeBuild(Build.java:239)
          at com.facebook.buck.command.Build.executeAndPrintFailuresToConsole(Build.java:271)
          at com.facebook.buck.cli.BuildCommand.runCommandWithOptionsInternal(BuildCommand.java:138)
          at com.facebook.buck.cli.BuildCommand.runCommandWithOptionsInternal(BuildCommand.java:1)
          at com.facebook.buck.cli.AbstractCommandRunner.runCommandWithOptions(AbstractCommandRunner.java:136)
          at com.facebook.buck.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:108)
          at com.facebook.buck.cli.Command.execute(Command.java:130)
          at com.facebook.buck.cli.Main.executeCommand(Main.java:652)
          at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:457)
          at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1016)
          at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1073)
          at com.facebook.buck.cli.Main.nailMain(Main.java:1102)
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
          at java.lang.reflect.Method.invoke(Method.java:497)
          at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
  Caused by: java.lang.NullPointerException
          at com.facebook.buck.step.fs.CopyStep.getDescription(CopyStep.java:106)
          at com.facebook.buck.step.DefaultStepRunner.runStepInternal(DefaultStepRunner.java:66)
          at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:55)
          at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:613)
          at com.facebook.buck.rules.CachingBuildEngine.buildOnceDepsAreBuilt(CachingBuildEngine.java:428)
          at com.facebook.buck.rules.CachingBuildEngine.access$3(CachingBuildEngine.java:348)
          at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:200)
          at com.facebook.buck.rules.CachingBuildEngine$1.onSuccess(CachingBuildEngine.java:1)
          at com.facebook.buck.util.concurrent.MoreFutures$1.onSuccess(MoreFutures.java:130)
          at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
          at java.lang.Thread.run(Thread.java:745)

and nothing was printed to the debug logs.

Now, it includes the stack trace in the debug logs.