Improve handling of failed toolchains when deciding if daemon should be restarted
Summary:
The current logic to decide whether daemon needs to be restarted doesn't handle properly cases when some toolchain has wrong configuration (and fails to be created).

For example, if a configuration was changed from invalid to a different configuration, daemon won't be restarted and Buck would fail with the old message.

This change adjusts the logic to properly use the failed state of a toolchain to decide if the state was changed.

Test Plan:
Steps for manual testing:

```
$ ANDROID_HOME=/111 ANDROID_SDK=/444 buck build some-android-app
UNKNOWN ERROR: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_SDK' points to an invalid directory '/444'.
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_SDK' points to an invalid directory '/444'.
$ ANDROID_HOME=/valid/android_sdk/location buck build some-android-app
...
UNKNOWN ERROR: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_SDK' points to an invalid directory '/444'.
com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.toolchain.ToolchainInstantiationException: Configuration 'ANDROID_SDK' points to an invalid directory '/444'.
```

After these changes the second command works fine.

Reviewed By: ttsugriy

fbshipit-source-id: e36c8ca