Fix MergeAndroidResourcesExecutableMain enum error
Summary:
Running `buck2 build //fbandroid/apps/fb4a/fastparse/flavors:fbandroid_64bit_exo-native --target-platforms=fbsource//tools/build_defs/config/platform/android:fb4a-64bit-debug`
(when rebased onto of this stack of patches D36645701) gives this error P503824830
```
java.lang.IllegalArgumentException: No enum constant com.facebook.buck.android.aapt.RDotTxtEntry.RType.anim
```
Because of enum case sensitivity, the lowercase inputs used for the failing function
https://www.internalfb.com/code/fbsource/[ba06487f5d01b7056bb9170c9a58381eec16426a]/fbcode/buck2/prelude/attributes.bzl?lines=125
Cause [`RType.valueOf()`](https://fburl.com/code/nfciapl4) to throw an exception
`RType` type: https://fburl.com/code/gyrvges2

Reviewed By: IanChilds

fbshipit-source-id: d6becbe86b28def3d74cb303ae3c6bc934a93af6