1.5.0 - incorrect metadata assertion
Summary:
`KotlinClassMetadata.read()` returns null if it can't process metadata.
Kotlin 1.5.0 uses a newer version of metadata, as a result class-abi missed all inline functions.
And build silently creates an incorrect ABI.

This diff adds a corresponding assertion:

```
java.lang.AssertionError: Unsupported kind of Kotlin classes: [1] or has an unsupported metadata version: [[1, 5, 1]]
```
Instead of failing a target `Foo` that depends on `Bar#class-abi` (`Bar` is Kotlin, has inline function, and compiled with kotlinc 1.5.0+) we will fail `Bar#class-abi` compilation.

Next diff(s) add fixes.

Before:
{F615551065}

After:
{F615551131}

Resolves: https://github.com/facebook/buck/issues/2620

Reviewed By: jkeljo

fbshipit-source-id: 887c15d7a79386f46f37bfcd480445e3bdeae817