Add missing concurrency annotations
Summary:
```
ERROR: ~/local/buck/src/com/facebook/buck/distributed/BUILD:3:1: Building src/com/facebook/buck/distributed/libdistributed.jar (46 source files) failed: Worker process sent response with exit code: 1.
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:80: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
          durationsMsByType.get(DistBuildClientStat.PERFORM_LOCAL_BUILD),
          ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:85: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
        durationsMsByType.get(DistBuildClientStat.PERFORM_DISTRIBUTED_BUILD),
        ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:88: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
        durationsMsByType.get(DistBuildClientStat.CREATE_DISTRIBUTED_BUILD),
        ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:91: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
        durationsMsByType.get(DistBuildClientStat.UPLOAD_MISSING_FILES),
        ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:94: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
        durationsMsByType.get(DistBuildClientStat.UPLOAD_TARGET_GRAPH),
        ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:97: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
        durationsMsByType.get(DistBuildClientStat.UPLOAD_BUCK_DOT_FILES),
        ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:100: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
        durationsMsByType.get(DistBuildClientStat.SET_BUCK_VERSION),
        ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:107: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
    if (!durationsMsByType.containsKey(stat)) {
         ^
    (see http://errorprone.info/bugpattern/GuardedBy)
src/com/facebook/buck/distributed/DistBuildClientStatsTracker.java:111: error: [GuardedBy] This access should be guarded by 'this', which is not currently held
    return Optional.of(durationsMsByType.get(stat));
                       ^
    (see http://errorprone.info/bugpattern/GuardedBy)
Target //src/com/facebook/buck/cli:cli failed to build
```

Test Plan: buck test ...

Reviewed By: dinhviethoa

fbshipit-source-id: 3f1bbcb