Merge Spring Framework resources.
Summary:
While building a Jar need to merge `spring.factories` files from different Spring libraries.
Required for Spring Boot autoconfiguration
```
java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories.
```

fbshipit-source-id: 45058dab4cf228bb4e794ed21939203124ad1b47