Don't print Java errors twice
Summary:
When Buck changed to include Java errors in the log, it actually
ended up printing them to the console twice. Fixing that.

Test Plan:
Introduce a Java error; verify it shows up exactly once. Tried with `tools.javac` set in addition to with the built-in compiler.

Before:
```
% bin/buck build buck
Shutting down nailgun server...
Using watchman.
No Android platform target specified. Using default: android-23
/Users/jkeljo/buck/src/com/facebook/buck/jvm/java/JavacStep.java:33: error: package com.facebook.buck.util.string does not exist
import com.facebook.buck.util.string.StringsUtils;
                                    ^
Errors: 1. Warnings: 0.

Rule //src/com/facebook/buck/jvm/java:steps has failed to build.
com.facebook.buck.util.string
com.facebook.buck.util.string.StringsUtils
Try adding the following deps:
//src/com/facebook/buck/util/string:string

BUILD FAILED: //src/com/facebook/buck/jvm/java:steps failed with exit code 1:
javac_jar
stderr: /Users/jkeljo/buck/src/com/facebook/buck/jvm/java/JavacStep.java:33: error: package com.facebook.buck.util.string does not exist
import com.facebook.buck.util.string.StringsUtils;
                                    ^
Errors: 1. Warnings: 0.

[-] PROCESSING BUCK FILES...FINISHED 4.8s [100%] ð  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 24.3s [100%] (525/650 JOBS, 524 UPDATED, 519 [79.8%] CACHE MISS)
```

After:
```
% bin/buck build buck
Shutting down nailgun server...
Using watchman.
No Android platform target specified. Using default: android-23
/Users/jkeljo/buck/src/com/facebook/buck/jvm/java/JavacStep.java:33: error: package com.facebook.buck.util.string does not exist
import com.facebook.buck.util.string.StringsUtils;
                                    ^
Errors: 1. Warnings: 0.

Rule //src/com/facebook/buck/jvm/java:steps has failed to build.
com.facebook.buck.util.string
com.facebook.buck.util.string.StringsUtils
Try adding the following deps:
//src/com/facebook/buck/util/string:string

BUILD FAILED: //src/com/facebook/buck/jvm/java:steps failed with exit code 1:
javac_jar
[-] PROCESSING BUCK FILES...FINISHED 4.4s [100%] ð  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 23.7s [100%] (522/650 JOBS, 521 UPDATED, 516 [79.4%] CACHE MISS)
```

Reviewed By: illicitonion

fbshipit-source-id: b9dfdf9