Fix LOG.verbose
Summary:
Without this, Buck crashes when FINER logging is enabled:
```
buck build  mode/opt common/hs/ide:hs-ide#ghci,platform009-clang
Starting new Buck daemon...
Buck daemon started.
Invalidating internal cached state: Buck configuration options changed between invocations. This may cause slower builds.
  Changed value //project.buck_out='buck-out/opt' (was 'buck-out/dev')
  ... and 277 more. See logs for all changes
Parsing buck files: finished in 11.1 sec
Creating action graph: finished in 33.9 sec
Building: finished in 3.6 sec
  Total time: 48.7 sec
BUILD FAILED
Buck encountered an internal error
com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: null: java.util.concurrent.ExecutionException: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When creating rule //common/hs/ide:hs-ide#ghci,platform009-clang.: java.util.MissingFormatArgumentException: Format specifier '%s'
	at com.facebook.buck.util.concurrent.MoreFutures.getUncheckedInterruptibly(MoreFutures.java:191)
	at com.facebook.buck.core.model.actiongraph.computation.ParallelActionGraphFactory.create(ParallelActionGraphFactory.java:105)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphFactory.createActionGraph(ActionGraphFactory.java:153)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphProvider.createActionGraph(ActionGraphProvider.java:209)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphProvider.getActionGraph(ActionGraphProvider.java:152)
	at com.facebook.buck.cli.AbstractBuildCommand.createActionGraphAndResolver(AbstractBuildCommand.java:271)
	at com.facebook.buck.cli.BuildCommand.createGraphsAndTargets(BuildCommand.java:89)
	at com.facebook.buck.cli.AbstractBuildCommand.executeBuildAndProcessResult(AbstractBuildCommand.java:441)
	at com.facebook.buck.cli.AbstractBuildCommand.run(AbstractBuildCommand.java:396)
	at com.facebook.buck.cli.AbstractBuildCommand.runWithoutHelpInternal(AbstractBuildCommand.java:338)
	at com.facebook.buck.cli.AbstractBuildCommand.runWithoutHelp(AbstractBuildCommand.java:320)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:44)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:274)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:92)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1585)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:517)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
Caused by: java.util.concurrent.ExecutionException: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When creating rule //common/hs/ide:hs-ide#ghci,platform009-clang.: java.util.MissingFormatArgumentException: Format specifier '%s'
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:507)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.facebook.buck.util.concurrent.MoreFutures.getUncheckedInterruptibly(MoreFutures.java:186)
	... 22 more
Caused by: com.facebook.buck.core.exceptions.BuckUncheckedExecutionException: When creating rule //common/hs/ide:hs-ide#ghci,platform009-clang.: java.util.MissingFormatArgumentException: Format specifier '%s'
	at com.facebook.buck.core.rules.transformer.impl.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:133)
	at com.facebook.buck.core.rules.transformer.impl.LegacyRuleAnalysisDelegatingTargetNodeToBuildRuleTransformer.transform(LegacyRuleAnalysisDelegatingTargetNodeToBuildRuleTransformer.java:138)
	at com.facebook.buck.core.rules.transformer.impl.LegacyRuleAnalysisProviderCompatibleTargetNodeToBuildRuleTransformer.transform(LegacyRuleAnalysisProviderCompatibleTargetNodeToBuildRuleTransformer.java:91)
	at com.facebook.buck.core.rules.resolver.impl.MultiThreadedActionGraphBuilder.lambda$addRequireTask$14(MultiThreadedActionGraphBuilder.java:243)
	at com.facebook.buck.core.rules.resolver.impl.MultiThreadedActionGraphBuilder$Task.tryComplete(MultiThreadedActionGraphBuilder.java:337)
	at com.facebook.buck.core.rules.resolver.impl.MultiThreadedActionGraphBuilder$Task.tryComplete(MultiThreadedActionGraphBuilder.java:326)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.facebook.buck.core.util.log.Logger.logAppendableLogRecord(Logger.java:357)
	at com.facebook.buck.core.util.log.Logger.verbose(Logger.java:128)
	at com.facebook.buck.core.util.log.Logger.verbose(Logger.java:109)
	at com.facebook.buck.features.haskell.HaskellGhciDescription.getOmnibusSpec(HaskellGhciDescription.java:163)
	at com.facebook.buck.features.haskell.HaskellDescriptionUtils.requireGhciRule(HaskellDescriptionUtils.java:471)
	at com.facebook.buck.features.haskell.HaskellBinaryDescription.createBuildRule(HaskellBinaryDescription.java:151)
	at com.facebook.buck.features.haskell.HaskellBinaryDescription.createBuildRule(HaskellBinaryDescription.java:75)
	at com.facebook.buck.core.rules.transformer.impl.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:123)
	... 8 more

    When creating rule //common/hs/ide:hs-ide#ghci,platform009-clang.
```

Reviewed By: josefs

fbshipit-source-id: 8156940e31d94c2abc0d5142c791608b7bedc2a6