Fix IllegalStateException in DefaultAndroidDirectoryResolver
Summary:
The toString method was not checking the right optional value for build tools which caused an IllegalStateException.

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:49)
	at com.facebook.buck.android.DefaultAndroidDirectoryResolver.toString(DefaultAndroidDirectoryResolver.java:432)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.facebook.buck.rules.Cell.toString(Cell.java:340)

Test Plan: ant test

Reviewed By: Coneko

fbshipit-source-id: 3cb6f6d