Adding --force when pushing to gh-pages seems to fix things.
Summary:
Previously, publish.sh was failing with complaints of:

   ! [rejected]        HEAD -> gh-pages (non-fast-forward)
  error: failed to push some refs to 'git@github.com:facebook/buck.git'
  To prevent you from losing history, non-fast-forward updates were rejected
  Merge the remote changes (e.g. 'git pull') before pushing again.  See the
  'Note about fast-forwards' section of 'git push --help' for details.

Presumably this is because I am doing some funny stuff with `--orphan`.
Using `--force` appears to fix things.

Test Plan: Manually tried this and it worked.