releasing `buck_package._lock_file` before deleting `tmp_dir`
Summary:
_lock_file should be closed when `programs.buck_project.BuckProject#__exit__` is called. Otherwise on windows:

```
Not using buckd because NO_BUCKD is set.
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 320, in execute
  File ".bootstrap/_pex/pex.py", line 253, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 285, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 363, in _execute
  File ".bootstrap/_pex/pex.py", line 421, in execute_entry
  File ".bootstrap/_pex/pex.py", line 426, in execute_module
  File "C:\Python27\lib\runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "programs/buck.py", line 48, in <module>
  File "programs/buck.py", line 41, in main
  File "programs/buck_project.py", line 123, in __exit__
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\...\\buck-out\\tmp\\buck_run.li8_hw\\resources\\f3a68d697ecc30b1e281a8a0d469b3a218f52465\\.buck_lock
```

Test Plan: CI. On windows: `python buck-out\gen\programs\buck.pex targets` before (leads to `WindowsError: [Error 32]`) and after (no error)

Reviewed By: marcinkosiba

fbshipit-source-id: 4239361