Improve error message when rulekey computation fails
Summary:
Before:
```
Buck encountered an internal error
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /private/var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/junit-temp-path2174256716220806389/buck-out/gen/native/fakenative/jni/__libfakenative
	at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:150)
	at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:100)
	at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:52)
	at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:41)
	at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:30)
	at com.facebook.buck.rules.keys.AlterRuleKeys.amendKey(AlterRuleKeys.java:49)
	at com.facebook.buck.rules.keys.AlterRuleKeys.amendKey(AlterRuleKeys.java:32)
	at com.facebook.buck.rules.keys.RuleKeyFieldLoader.setFields(RuleKeyFieldLoader.java:56)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.newPopulatedBuilder(DefaultRuleKeyFactory.java:78)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.lambda$build$0(DefaultRuleKeyFactory.java:106)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.calculateNode(DefaultRuleKeyCache.java:116)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.lambda$null$1(DefaultRuleKeyCache.java:137)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.getNode(DefaultRuleKeyCache.java:138)
	at com.facebook.buck.rules.keys.DefaultRuleKeyCache.get(DefaultRuleKeyCache.java:154)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:103)
	at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:38)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$calculateRuleKey$8(CachingBuildEngine.java:473)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /private/var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/junit-temp-path2174256716220806389/buck-out/gen/native/fakenative/jni/__libfakenative
		at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:150)
		at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:100)
		at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:52)
		at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:41)
		at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:30)
		at com.facebook.buck.rules.keys.AlterRuleKeys.amendKey(AlterRuleKeys.java:49)
		at com.facebook.buck.rules.keys.AlterRuleKeys.amendKey(AlterRuleKeys.java:32)
		at com.facebook.buck.rules.keys.RuleKeyFieldLoader.setFields(RuleKeyFieldLoader.java:56)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.newPopulatedBuilder(DefaultRuleKeyFactory.java:78)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.lambda$build$0(DefaultRuleKeyFactory.java:106)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.calculateNode(DefaultRuleKeyCache.java:116)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.lambda$null$1(DefaultRuleKeyCache.java:137)
		at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.getNode(DefaultRuleKeyCache.java:138)
		at com.facebook.buck.rules.keys.DefaultRuleKeyCache.get(DefaultRuleKeyCache.java:154)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:103)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:38)
		at com.facebook.buck.rules.BuildRuleEvent$Suspended.<init>(BuildRuleEvent.java:322)
		at com.facebook.buck.rules.BuildRuleEvent$Suspended.<init>(BuildRuleEvent.java:316)
		at com.facebook.buck.rules.BuildRuleEvent$FinishedRuleKeyCalc.<init>(BuildRuleEvent.java:378)
		at com.facebook.buck.rules.BuildRuleEvent$FinishedRuleKeyCalc.<init>(BuildRuleEvent.java:373)
		at com.facebook.buck.rules.BuildRuleEvent.ruleKeyCalculationFinished(BuildRuleEvent.java:112)
		at com.facebook.buck.rules.BuildRuleEvent.lambda$ruleKeyCalculationScope$0(BuildRuleEvent.java:415)
		at com.facebook.buck.rules.CachingBuildEngine.lambda$calculateRuleKey$8(CachingBuildEngine.java:474)
		... 13 more
	Caused by: java.nio.file.NoSuchFileException: /private/var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/junit-temp-path2174256716220806389/buck-out/gen/native/fakenative/jni/__libfakenative
		at com.facebook.buck.util.cache.impl.StackedFileHashCache.lambda$get$0(StackedFileHashCache.java:192)
		at java.util.Optional.orElseThrow(Optional.java:290)
		at com.facebook.buck.util.cache.impl.StackedFileHashCache.get(StackedFileHashCache.java:192)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:210)
		at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:159)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:181)
		at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:148)
		at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:148)
		... 36 more
```
After:
```
Build failed: java.nio.file.NoSuchFileException /private/var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/junit-temp-path2500881556297568283/buck-out/gen/native/fakenative/jni/__libfakenative
    When adding nativeLibDirectories with value [/private/var/folders/r9/391dwttx57j408_mr2chwb_d14d45q/T/junit-temp-path2500881556297568283/buck-out/gen/native/fakenative/jni/__libfakenative]
    When computing rulekey for //apps/sample:app_with_ndk_library#copy_native_libs_dex.
```

Test Plan: CI, did build with such a failure and saw better error message

Reviewed By: ttsugriy

fbshipit-source-id: 3dab431