Add missing http libraries for buck publish command to work
TEST PLAN:

  $ buck publish --remote-repo <foo> //:bar

isn't failing with:

  java.lang.NoClassDefFoundError: org/apache/http/client/HttpResponseException