Support Go Subtests
Summary:
Go 1.7 introduced subtests, which will print out report like this:

```
=== RUN   TestTime
=== RUN   TestTime/12:31_in_Europe/Zuri
=== RUN   TestTime/12:31_in_America/New_York
=== RUN   TestTime/08:08_in_Australia/Sydney
 --- FAIL: TestTime (0.00s)
    --- FAIL: TestTime/12:31_in_Europe/Zuri (0.00s)
    	command_test.go:23: could not load location
    --- PASS: TestTime/12:31_in_America/New_York (0.00s)
    --- PASS: TestTime/08:08_in_Australia/Sydney (0.00s)
```

This PR make Buck capable of consuming such test report.
Closes https://github.com/facebook/buck/pull/1740

Reviewed By: styurin

Pulled By: styurin

fbshipit-source-id: 11d4e1f