Add more descriptive error message when an artefact cache returns invalid metadata.
Summary:
Sometimes the artefact cache can serve corrupt metadata. Provide a more descriptive
error message in that case.

Test Plan:
$ bin/buck build --config cache.mode=dir --config build.engine=deep buck
# corrupt a rule key metadata in the dir cache (for example by replacing some digits with 'h'.
# note the length of the key should be correct or the artefact will be ignored.
$ bin/buck build --config cache.mode=dir --config build.engine=deep buck
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🏖  (Watchman reported no changes)
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 1.5s [100%] (43/933 JOBS, 43 UPDATED, 1 [0.1%] CACHE MISS)
[2017-06-13 16:39:12.311][error][command:null][tid:610][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid 'RULE_KEY' rule key in metadata for artifact 'd8bec52742f7c1989311849fc2685993b186ba62' returned by cache 'class com.facebook.buck.artifact_cache.TwoLevelArtifactCacheDecorator': 'd8behhhh42f7c1989311849fc2685993b186ba62'
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:382)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:924)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:855)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:509)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:415)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:381)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:66)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:968)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:351)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1856)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid 'RULE_KEY' rule key in metadata for artifact 'd8bec52742f7c1989311849fc2685993b186ba62' returned by cache 'class com.facebook.buck.artifact_cache.TwoLevelArtifactCacheDecorator': 'd8behhhh42f7c1989311849fc2685993b186ba62'
	at com.facebook.buck.command.Build.executeBuild(Build.java:278)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:331)
	... 16 more
Caused by: java.lang.IllegalArgumentException: Invalid 'RULE_KEY' rule key in metadata for artifact 'd8bec52742f7c1989311849fc2685993b186ba62' returned by cache 'class com.facebook.buck.artifact_cache.TwoLevelArtifactCacheDecorator': 'd8behhhh42f7c1989311849fc2685993b186ba62'
	at com.facebook.buck.rules.CachingBuildEngine.fetch(CachingBuildEngine.java:1451)
	at com.facebook.buck.rules.CachingBuildEngine.tryToFetchArtifactFromBuildCacheAndOverlayOnTopOfProjectFilesystem(CachingBuildEngine.java:1416)
	at com.facebook.buck.rules.CachingBuildEngine.performRuleKeyCacheCheck(CachingBuildEngine.java:583)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$2(CachingBuildEngine.java:475)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Illegal hexadecimal character: h
	at com.google.common.hash.HashCode.decode(HashCode.java:368)
	at com.google.common.hash.HashCode.fromString(HashCode.java:354)
	at com.facebook.buck.rules.CachingBuildEngine.fetch(CachingBuildEngine.java:1449)
	... 11 more

Reviewed By: shivanker

fbshipit-source-id: 293831c