javacd: specify UTF-8 encoding when launch a process
Summary:
If I am trying to execute buck build with javacd and RE then I have the following issue:

```
INFO: Target: //third-party/java/guava:guava#source-abi SpoolMode: DIRECT_TO_JAR Expected SpoolMode: DIRECT_TO_JAR Postprocessing steps: []
/remote_execution/tmp/execution/0/c5ace6de2cd044e29a09a395190dbb3e/work/third-party/java/guava/android/guava/src/com/google/common/base/Stopwatch.java:236: error: unmappable character (0xCE) for encoding US-ASCII
        return "μs"; // ??s
                             ^
/remote_execution/tmp/execution/0/c5ace6de2cd044e29a09a395190dbb3e/work/third-party/java/guava/android/guava/src/com/google/common/base/Stopwatch.java:236: error: unmappable character (0xBC) for encoding US-ASCII
        return "μs"; // ??s
                              ^
/remote_execution/tmp/execution/0/c5ace6de2cd044e29a09a395190dbb3e/work/third-party/java/guava/android/guava/src/com/google/common/base/Utf8.java:36: error: unmappable character (0xC3) for encoding US-ASCII
 * author Cl??ment Roux
             ^
```
That means that by default RE worker uses `US-ASCII` encoding that is wrong.

With specifying encoding in the JVM startup command this issue no longer present.

Reviewed By: bobyangyf

fbshipit-source-id: bf6f631ce5835c66a108db849c8d892cae5e03f5