Fix buck build buck
Summary:
buck build buck was broken by b50c6d26b8 ("Load
TranslatingJavacPhaseTracer from resources"), with the following error
message:
/home/tommy/work/buck/src/com/facebook/buck/java/Jsr199Javac.java:171: error: cannot access com.facebook.buck.java.tracing.JavacPhaseTracer
      TranslatingJavacPhaseTracer.setupTracing(
                                 ^
  class file for com.facebook.buck.java.tracing.JavacPhaseTracer not found
Errors: 1. Warnings: 1.

This is because of a missing dependency.  Add the dependency to fix the
build.

Test plan:
Check that buck build buck compiles buck successfully.