windows: error message w/o period in the end
Summary:
From error message:
```
com.facebook.buck.io.namedpipes.PipeNotConnectedException: ReadFile() failed. Named pipe: \\.\pipe\buck-7fa98c36-4ed7-4c6d-8823-20641552140c, error: The handle is invalid.. Opened handles: 1
```

`error: The handle is invalid..` has 2 consecutive `.`s

Seems like `Kernel32Util.formatMessageFromLastErrorCode()` returns a message with `.` in the end, so no need to add an extra `.` in the message format.

Reviewed By: bobyangyf

fbshipit-source-id: 80876bd2dcf92412c3988b203e26346d8f28782a