Convert integer entries to hex decimal entries during RDotTxtEntry initialization.
Summary:
__Problem:__
Android attributes are being populated to R.java created by mini aapt like `android_font`. This causes robolectric test failures. ([fails to construct Robolectric resource table](https://github.com/robolectric/robolectric/blob/b019ccaad2ab76a632306956c71c4bcdc730e95b/resources/src/main/java/org/robolectric/res/PackageResourceTable.java#L109))
```
java.lang.IllegalArgumentException: Incompatible package for com.uber:attr/android_font with resId 1 to ResourceIndex with packageIdentifier 7
    at org.robolectric.res.PackageResourceTable.addResource(PackageResourceTable.java:109)
    at org.robolectric.res.ResourceTableFactory.addRClassValues(ResourceTableFactory.java:71)
    at org.robolectric.res.ResourceTableFactory.lambda$newResourceTable$1(ResourceTableFactory.java:45)
    at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
    at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:38)
    at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:20)
    at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:529)
    ...
```

__RootCause:__
This is happening because a third party library is including `android_font` in its R.txt with an integer value. The attribute is then included in the dependee's R.java generated by miniaapt.

__Solution:__
Don't include any attributes which starts with `"0x01"`, since those should come from the android framework. Also need make `RDotTxtEntry` initialization convert integers into hexdecimal strings so that the check is effective.

This only affects R.java files generated for robolectric tests and intermediatray libraries.
Closes https://github.com/facebook/buck/pull/1797

Reviewed By: styurin

Pulled By: styurin

fbshipit-source-id: bb8ebbb