Improve Sha1HashCode.getHash
Summary:
There is no need to manually change endianess only to then instantiate String Formatter multiple times.
This is about 40x faster for whatever little that means in the grand scheme of things.

Test Plan:
Existing unit tests.

Perf test:

  Test
  public void testNewToString() {
    Sha1HashCode sha1 = Sha1HashCode.of("a002b39af204cdfaa5fdb67816b13867c32ac52c");
    long T0 = System.nanoTime();
    for (int i = 0; i < 10000000; i++) {
      String s = sha1.getHashOld();
    }
    long T1 = System.nanoTime();
    for (int i = 0; i < 10000000; i++) {
      String s = sha1.getHash();
    }
    long T2 = System.nanoTime();
    double dt1 = (T1 - T0) / 1e9;
    double dt2 = (T2 - T1) / 1e9;
    double speedup = dt1 / dt2;
    fail(String.format("old: %.3f, new: %.3f, speedup: %.3fx", dt1, dt2, speedup));
  }

  java.lang.AssertionError: old: 21.028, new: 0.508, speedup: 41.366x
  java.lang.AssertionError: old: 20.427, new: 0.532, speedup: 38.397x

Reviewed By: Coneko, bolinfest

fbshipit-source-id: 214b0f2