Adjusted FileFinder import to work with Python 3.6 (#318)
Summary:
This is a port of pex commit c5ab73fd4d8e816e21a89d48c8d0c8095ef5a49c to make
PEX work properly on Python 3.6.

Currently a buck-built PEX gives the following error:
```
  File ".bootstrap/_pex/pex_bootstrapper.py", line 94, in bootstrap_pex
  File ".bootstrap/_pex/finders.py", line 218, in register_finders
AttributeError: module 'importlib._bootstrap' has no attribute 'FileFinder'
```

Original commit message:

```
In CPython 3.6, FileFinder has been moved from importlib._bootstrap to
a new importlib._bootstrap_external module.

To account for this, this commit switches to importing the more general
importlib.machinery module instead of importlib._bootstrap, which also
works with older CPython version (3.3+).
```

Test Plan: `buck run <python target>` on a Python 3.6 platform.

Reviewed By: dinhviethoa

fbshipit-source-id: 4128c06